import { ISuperTableColumn, ISuperTableFilter, superTableFilters } from "ngx-super-table";

const employeColumns:ISuperTableColumn[] = [
    { label: 'Prenoms', id: 'prenoms', key: 'prenoms', filter: superTableFilters.STRING },
    { label: 'Nom', id: 'nom', key: 'nom' },
    { label: 'Date Naissance', id: 'dateNaissance', key: 'dateNaissance', filter: superTableFilters.STRING },
    { label: 'Lieu Naissance', id: 'lieuNaissance', key: 'lieuNaissance', filter: superTableFilters.STRING },
    { label: 'Cni', id: 'cni', key: 'cni', filter: superTableFilters.STRING },
    { label: 'Matricule', id: 'matricule', key: 'matricule', filter: superTableFilters.STRING },
    { label: 'Matricule Caisse Sociale', id: 'matriculeCaisseSociale', key: 'matriculeCaisseSociale', filter: superTableFilters.STRING },
    { label: 'Date Recrutement', id: 'dateRecrutement', key: 'dateRecrutement', filter: superTableFilters.STRING },
    { label: 'Situtation Matrimoniale', id: 'situtationMatrimoniale', key: 'situtationMatrimoniale', filter: superTableFilters.STRING },
    { label: 'Genre', id: 'genre', key: 'genre', filter: superTableFilters.STRING },
    { label: 'Etat', id: 'etat', key: 'etat', filter: superTableFilters.STRING },
    { label: 'Email Univ', id: 'emailUniv', key: 'emailUniv', filter: superTableFilters.STRING },
    { label: 'Email', id: 'email', key: 'email', filter: superTableFilters.STRING },
    { label: 'Filename', id: 'filename', key: 'filename', filter: superTableFilters.STRING },
    { label: 'Filepath', id: 'filepath', key: 'filepath', filter: superTableFilters.STRING },
    { label: 'Telephone Primaire', id: 'telephonePrimaire', key: 'telephonePrimaire', filter: superTableFilters.STRING },
    { label: 'Telephone Secondaire', id: 'telephoneSecondaire', key: 'telephoneSecondaire', filter: superTableFilters.STRING },
    { label: 'Type Employe', id: 'typeEmploye', key: 'typeEmploye', filter: superTableFilters.STRING },
    { label: 'Nationalite', id: 'nationalite', key: 'nationalite', filter: superTableFilters.STRING },
    { label: 'Caisse Sociale', id: 'caisseSociale', key: 'caisseSociale', filter: superTableFilters.STRING },
    { label: 'Mutuelle Sante', id: 'mutuelleSante', key: 'mutuelleSante', filter: superTableFilters.STRING },
    { label: 'Grade', id: 'grade', key: 'grade', filter: superTableFilters.STRING },
    { label: 'Structure', id: 'structure', key: 'structure', filter: superTableFilters.STRING },
    { label: 'Date Prise Service', id: 'datePriseService', key: 'datePriseService', filter: superTableFilters.DATE },
    { label: 'Date Sortie', id: 'dateSortie', key: 'dateSortie', filter: superTableFilters.DATE },
    { label: 'Motif Sortie', id: 'motifSortie', key: 'motifSortie', filter: superTableFilters.STRING },
    { label: 'Numero Main Oeuvre', id: 'numeroMainOeuvre', key: 'numeroMainOeuvre', filter: superTableFilters.STRING },
    { label: 'Numero Affiliation Ipres', id: 'numeroAffiliationIpres', key: 'numeroAffiliationIpres', filter: superTableFilters.STRING },
    { label: 'Profession', id: 'profession', key: 'profession', filter: superTableFilters.STRING },
    { label: 'Commentaire Sortie', id: 'commentaireSortie', key: 'commentaireSortie', filter: superTableFilters.STRING }

];

const allowedEmployeidsForFilter : ISuperTableFilter [] = [
    {type: 'TEXT', title: 'prenoms', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) => true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'nom', isActive: (filterValue: any) =>true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Nom'},
    {type: 'TEXT', title: 'dateNaissance', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Date Naissance'},
    {type: 'TEXT', title: 'lieuNaissance', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Lieu Naissance'},
    {type: 'TEXT', title: 'cni', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Cni'},
    {type: 'TEXT', title: 'matricule', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Matricule'},
    {type: 'TEXT', title: 'matriculeCaisseSociale', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'dateRecrutement', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'situtationMatrimoniale', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'genre', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'etat', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'emailUniv', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'email', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'filename', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'filepath', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'telephonePrimaire', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'telephoneSecondaire', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'typeEmploye', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'nationalite', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'caisseSociale', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'mutuelleSante', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'grade', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'structure', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'datePriseService', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'dateSortie', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'motifSortie', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'numeroMainOeuvre', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'numeroAffiliationIpres', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'profession', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'},
    {type: 'TEXT', title: 'commentaireSortie', isActive: (filterValue: any) => true, fn: (filterValue: any, value: any, row: Object) =>true, placeholder: 'Chercher Prenom'}
];


export { employeColumns, allowedEmployeidsForFilter };
